Endpoint republish
ant-media/Ant-Media-Server pull request #3620
Opened 2021-09-12 15:05 UTC by golgetahir

https://github.com/ant-media/Ant-Media-Server/issues/3547

2021-09-15 09:36 UTC, mekya requested changes
Please take a look the comments

2021-09-15 09:36 UTC, mekya commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +		retryLimit = appSettingsLocal.getEndpointRepublishLimit();
Please give a more descriptive name. `retryLimit` is so generic. It can be something `rtmpEndpointRetryLimit`

2021-09-15 09:36 UTC, mekya commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +	protected ConcurrentHashMap<String, Boolean> isHealthCheckGoing = new ConcurrentHashMap<>();
Please make names more descriptive in order to let anyone understand the code easily.

2021-09-15 09:36 UTC, mekya commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +			else if(statusMap.get(url).equals(IAntMediaStreamHandler.BROADCAST_STATUS_ERROR)){
What about the FAILED scenario?

2021-09-15 09:36 UTC, mekya commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +				isHealthCheckGoing.remove(url);
Do we need to reset retryCounter, errorCountMap?

2021-09-15 09:36 UTC, mekya commented on src/main/java/io/antmedia/muxer/MuxAdaptor.java
> +	@Override
Why is it on the super class?

2021-09-17 09:44 UTC, golgetahir commented
> Please take a look the comments

Done, thank you for the review.

2021-09-20 11:41 UTC, mekya commented
I recommend you to have an integration test for this case.

2021-09-23 16:17 UTC, mekya approved these changes

2021-09-23 16:17 UTC, mekya commented
Good work. Thank you 👍

2021-09-26 16:44 UTC, merged