add email address for letsencrypt
ant-media/Ant-Media-Server pull request #3801
Opened 2021-12-13 14:49 UTC by muratugureminoglu

https://github.com/ant-media/Ant-Media-Server/issues/3789

2021-12-26 19:20 UTC, mekya requested changes
Shall we make email parameter as optional?  Otherwise it breaks the compatibility and it will cause problem for the users. 

If email is present as parameter, we can use in certbot. 
If it's not present, we can call  with `--register-unsafely-without-email` as before

2022-01-01 18:19 UTC, mekya commented
A kind reminder for this PR @muratugureminoglu

2022-01-02 21:22 UTC, muratugureminoglu commented
> Shall we make email parameter as optional? Otherwise it breaks the compatibility and it will cause problem for the users.
> 
> If email is present as parameter, we can use in certbot. If it's not present, we can call with `--register-unsafely-without-email` as before

It 's done.

2022-01-16 17:46 UTC, mekya approved these changes
I've just changed the command line info and put the e-mail to the square brackets because e-mail is optional

2022-01-16 17:46 UTC, mekya commented on src/main/server/enable_ssl.sh
> +  echo "$0 -d {DOMAIN_NAME} [-i {INSTALL_DIRECTORY}] -e {YOUR_EMAIL}"
It seems that e-mail is optional. AFAIK, optional parameters are shown with square brackets

2022-01-16 19:06 UTC, merged