Issue #4748 symbolic links are deleted fix.
ant-media/Ant-Media-Server pull request #4789
Opened 2023-02-01 08:53 UTC by lastpeony

https://github.com/ant-media/Ant-Media-Server/issues/4748

2023-02-21 11:47 UTC, mekya requested changes
@lastpeony thank you for your work.  
We need to have unit test code to merge this PR because we don't want to encounter the same problem again in the future.

2023-02-21 21:50 UTC, lastpeony commented
> @lastpeony thank you for your work. We need to have unit test code to merge this PR because we don't want to encounter the same problem again in the future.

As i see unit test coverage is 100% on new code.
testSynchUserVoD in AntMediaApplicationAdapterUnitTest.java is covering it.

Did you mean functional test?

2023-02-25 06:40 UTC, mekya commented
Yes, a kind of functional test because there is a bug in the code and we don't want to encounter the same problem again in the same way in the future. 

I've implemented the test code as a reference. 
I mean you can just check it and implement the same way for your future PRs

2023-02-25 12:04 UTC, mekya commented on src/main/java/io/antmedia/AntMediaApplicationAdapter.java
> +				File newLinkFile = new File(streamsFolder, vodFolder.getName());
It's an expected behavior.  @sonatype-lift ignore

2023-02-25 12:04 UTC, mekya commented on src/main/java/io/antmedia/AntMediaApplicationAdapter.java
> +				File newLinkFile = new File(streamsFolder, vodFolder.getName());
@sonatype-lift ignore

2023-02-25 12:13 UTC, mekya commented on src/main/java/io/antmedia/AntMediaApplicationAdapter.java
> +				File newLinkFile = new File(streamsFolder, vodFolder.getName());
@sonatype-lift ignoreall

2023-02-25 12:14 UTC, mekya approved these changes

2023-02-25 12:14 UTC, merged