Add admin, presenter, publisher request and publisher from listener list into broadcast object
ant-media/Ant-Media-Server pull request #6148
Opened 2024-03-01 11:29 UTC by mustafaboleken

https://github.com/ant-media/Ant-Media-Server/issues/6147

2024-03-18 14:43 UTC, mekya requested changes
Thank you @mustafaboleken for the implementation. 

I see some opportunities to make it more simple. Here are my ideas, we can discuss it later

- No need to have new abstract methods in DataStore. updateBroadcast method is enough
-  No need to have `presenterList` field in broadcast object. They are subtracks of the main stream and there is a field for subtracks. 
- No need to have publisherFromListener because they are again subtracks.
- Rename publisherRequestList to `subtrackRequestList` or something similar

2024-03-18 14:43 UTC, mekya commented on src/main/java/io/antmedia/datastore/db/types/Broadcast.java
> +	List<String> publisherRequestList = new ArrayList<String>();
These are the subsriberId of the user or they are stream id?

2024-03-18 14:43 UTC, mekya commented on src/main/java/io/antmedia/datastore/db/types/Broadcast.java
> +	List<String> publisherFromListenerList = new ArrayList<String>();
Do we need to have different fields for user scenarios? I mean publisherFromListenerList seems like scenario specific to me.

2024-03-18 14:43 UTC, mekya commented on src/main/java/io/antmedia/datastore/db/types/Broadcast.java
> +	List<String> adminList = new ArrayList<String>();
These are the subscriberIds?

2024-03-18 14:43 UTC, mekya commented on src/main/java/io/antmedia/datastore/db/types/Broadcast.java
> +	List<String> presenterList = new ArrayList<String>();
presenterList is also the subtracks of this stream. Do we need to have additional field?

2024-03-18 14:43 UTC, mekya commented on src/main/java/io/antmedia/datastore/db/DataStore.java
> +	public abstract boolean addIntoPublisherRequestList(String mainTrackId, String streamId);
I think we don't need to additional methods for the new fields, we can just use the updateBroadcast method

2024-03-18 17:08 UTC, mustafaboleken commented
@mekya thank you for your review. I understand your points but for some scenarios, it's hard to keep track of subtracts. I will  ask them in a meeting.

2024-06-24 11:20 UTC, mekya commented
WILL NOT MERGED and we provide another resolution: Role based streaming

2024-06-24 11:51 UTC, closed without merging